In [1]:
import numpy as np
import matplotlib.pyplot as plt
from procesar_ecuacion import procesar_ecuacion

### Convertir ecuacións a numpy

Exemplo sobre como procesar unha lista de ecuacións en formato textual a un array de numpy utilizando o módulo `procesar_ecuacions.py`.

In [2]:
ecuacions = (
    "3x - 2y + 4z = 0",
    "5x + 3y - 2z = 3",
)

procesar_ecuacion(*ecuacions)

array([[ 3, -2,  4,  0],
       [ 5,  3, -2,  3]])

### Eliminación gaussiana sin pivoteo

In [5]:
ecuacions_s = (
    "2x1 -  x2 + x3  = 3",
    "-x1 +  x2 + 2x3 = 7",
    " x1 + 2x2 - x3  = 2",
)

ec, keys = procesar_ecuacion(*ecuacions_s, nomes=True)

print(ec)
print(keys)

[[ 2 -1  1  3]
 [-1  1  2  7]
 [ 1  2 -1  2]]
dict_keys(['x1', 'x2', 'x3', 'b'])
