In [1]:
import numpy as np
import matplotlib.pyplot as plt
from procesar_ecuacion import procesar_ecuacion

### Convertir ecuacións a numpy

Exemplo sobre como procesar unha lista de ecuacións en formato textual a un array de numpy utilizando o módulo `procesar_ecuacions.py`.

In [2]:
ecuacions = (
    "3x - 2y + 4z = 0",
    "5x + 3y - 2z = 3",
)

procesar_ecuacion(*ecuacions)

array([[ 3, -2,  4,  0],
       [ 5,  3, -2,  3]])

### Eliminación gaussiana sin pivoteo

In [16]:
# Obter a columna dun array 2D
columna = lambda a, n: a[:, n]

# Obter as matrices de coeficientes e o vector de termos independientes de un sistema conxunto
def dividir_sistema(ecuacions):
    coefs = np.array([x[:-1] for x in ecuacions])
    t_ind = np.array([x[-1] for x in ecuacions])
    return coefs, t_ind

# Inversa da función anterior, devolve un sistema combinado
def sistema_combinado(coefs, t_ind):
    return np.array([[x for x in coefs[i]] + [t_ind[i]] for i in range(len(coefs))])

# Transforma unha matriz nunha matriz triangular superior
def matriz_triangular_superior(ecuacions, fila_pivote=0):
    sistema = ecuacions.astype(float) # Sistema de ecuacions sobre o que operar
    n_filas = len(ec) # Número de filas
    n_columnas = len(ec[0]) # Número de columnas
    outras_filas = [f for f in range(n_filas) if f != fila_pivote] # Filas distintas da pivote

    # Iterar polos elementos do triángulo iferior da matriz
    for c in range(n_columnas):
        p = sistema[fila_pivote][c]

        for f in outras_filas:
            # Cálculo coeficiente
            k = sistema[f][c] / p
            print("Columna: {} - Fila: {} - a_{}{} / a_{}{} = {}".format(c+1, f+1, f+1, c+1, fila_pivote+1, c+1, k))
            
            # Restar a N final menos o producto do coeficiente pola fila pivote
            temp = np.copy(sistema[f])
            sistema[f] -= k * sistema[fila_pivote]
            print("{} -> {}".format(temp, sistema[f]))
        
        for f in outras_filas:
            if sistema[f][c] == 0:
                fila_pivote = f
                outras_filas.remove(f)
                break

        print("\nSistema reducido:\n{}".format(sistema))

        if len(outras_filas) == 0:
            break

        print("Nova fila pivote: {}\n".format(fila_pivote))

    return sistema


In [17]:
# Sistema de ecuacións plantexado

ecuacions_s = (
    "2x1 -  x2 + x3  = 3",
    "-x1 +  x2 + 2x3 = 7",
    " x1 + 2x2 - x3  = 2",
)

ec, keys = procesar_ecuacion(*ecuacions_s, nomes=True)
print("Sistema inicial:\n{}\n".format(ec))

sistema_reducido = matriz_triangular_superior(ec, 0)
print("\nSistema reducido:\n{}".format(sistema_reducido))

Sistema inicial:
[[ 2 -1  1  3]
 [-1  1  2  7]
 [ 1  2 -1  2]]

Columna: 1 - Fila: 2 - a_21 / a_11 = -0.5
[-1.  1.  2.  7.] -> [0.  0.5 2.5 8.5]
Columna: 1 - Fila: 3 - a_31 / a_11 = 0.5
[ 1.  2. -1.  2.] -> [ 0.   2.5 -1.5  0.5]

Sistema reducido:
[[ 2.  -1.   1.   3. ]
 [ 0.   0.5  2.5  8.5]
 [ 0.   2.5 -1.5  0.5]]
Nova fila pivote: 1

Columna: 2 - Fila: 3 - a_32 / a_22 = 5.0
[ 0.   2.5 -1.5  0.5] -> [  0.   0. -14. -42.]

Sistema reducido:
[[  2.   -1.    1.    3. ]
 [  0.    0.5   2.5   8.5]
 [  0.    0.  -14.  -42. ]]

Sistema reducido:
[[  2.   -1.    1.    3. ]
 [  0.    0.5   2.5   8.5]
 [  0.    0.  -14.  -42. ]]


In [15]:
# Sistema de ecuacións plantexado

ecuacions_s2 = (
    "2x1 -  x2 + x3  - 2x4 = 3",
    "-x1 +  x2 + 2x3 - 3x4 = 7",
    " x1 + 2x2 - x3  +  x4 = 2",
    "3x1 + 2x2 - x3  - 5x4 = 9",
)

ec_2, keys_2 = procesar_ecuacion(*ecuacions_s2, nomes=True)
print("Sistema inicial:\n{}\n".format(ec_2))

sistema_reducido_2 = matriz_triangular_superior(ec_2, 0)

Sistema inicial:
[[ 2 -1  1 -2  3]
 [-1  1  2 -3  7]
 [ 1  2 -1  1  2]
 [ 3  2 -1 -5  9]]


Columna: 1 - Fila: 2 - a_21 / a_11 = -0.5
[-1.  1.  2. -3.  7.] -> [ 0.   0.5  2.5 -4.   8.5]
Columna: 1 - Fila: 3 - a_31 / a_11 = 0.5
[ 1.  2. -1.  1.  2.] -> [ 0.   2.5 -1.5  2.   0.5]
Nova fila pivote: 1

Columna: 2 - Fila: 3 - a_32 / a_22 = 5.0
[ 0.   2.5 -1.5  2.   0.5] -> [  0.   0. -14.  22. -42.]


In [6]:
coefs, t_ind = dividir_sistema(ec)
print(coefs)
print(t_ind)

s_comb = sistema_combinado(coefs, t_ind)
print(s_comb)

[[ 2 -1  1]
 [-1  1  2]
 [ 1  2 -1]]
[3 7 2]
[[ 2 -1  1  3]
 [-1  1  2  7]
 [ 1  2 -1  2]]
